services:

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    environment:
      FRONTEND_PORT: "8000"
      WORKER_PORT: "4000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend
  
  listener:
    build:
      context: .
      dockerfile: docker/listener/Dockerfile
    container_name: listener
    environment:
      WORKER_PORT: "4000"
    volumes:
      - .:/app
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: worker
    environment:
      WORKER_PORT: "4000"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq        
    environment:
      RABBITMQ_ERLANG_COOKIE: secret
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend

networks:
  backend:
    driver: bridge
